<?php
/**
 * PWF PO System - Auto Setup Script
 * Jalankan di browser: https://adfsystem.online/setup-pwf.php
 * Script ini akan:
 * 1. Membuat/update config.php untuk PWF
 * 2. Import database schema
 * 3. Verifikasi koneksi database
 */

// Prevent direct execution if not HTTP
if (php_sapi_name() === 'cli') {
    die("Script ini hanya bisa dijalankan via browser, bukan CLI\n");
}

// Security: hanya untuk admin, cek IP atau token
$allowedIPs = ['127.0.0.1', 'localhost', '::1'];
$clientIP = $_SERVER['REMOTE_ADDR'] ?? '';
$isLocalhost = in_array($clientIP, $allowedIPs);
$token = $_GET['token'] ?? '';
$validToken = 'pwf_setup_2026'; // Change ini ke token unik

if (!$isLocalhost && $token !== $validToken) {
    die("⛔ Access Denied. Jalankan dari localhost atau gunakan token yang valid.");
}

echo "<h1>🚀 PWF PO System - Auto Setup</h1>";
echo "<pre>";

$success = true;
$targetDir = '/home/adfb2574/public_html/pwf-po-system';
$configPath = $targetDir . '/config/config.php';
$databasePath = $targetDir . '/database.sql';

// ===== STEP 1: Create config.php =====
echo "\n[STEP 1] Creating config.php...\n";

$configContent = <<<'CONFIG'
<?php
/**
 * PWF PO System - Configuration File
 * Auto-generated by setup script
 */

if (!ob_get_level()) {
    ob_start();
}

if (!defined('SESSION_NAME')) define('SESSION_NAME', 'PWF_SESSION');
if (!defined('SESSION_LIFETIME')) define('SESSION_LIFETIME', 3600 * 8);

if (session_status() === PHP_SESSION_NONE) {
    session_name(SESSION_NAME);
    $isSecure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off');
    session_set_cookie_params([
        'lifetime' => SESSION_LIFETIME,
        'path' => '/',
        'secure' => $isSecure,
        'httponly' => true,
        'samesite' => 'Lax'
    ]);
    session_start();
}

defined('APP_ACCESS') or define('APP_ACCESS', true);

if (!defined('APP_NAME')) define('APP_NAME', 'PWF PO System - Purchase Order Management');
if (!defined('APP_VERSION')) define('APP_VERSION', '1.0.0');
if (!defined('APP_YEAR')) define('APP_YEAR', '2026');
if (!defined('DEVELOPER_NAME')) define('DEVELOPER_NAME', 'Ariefsystemdesign.net');
if (!defined('DEVELOPER_LOGO')) define('DEVELOPER_LOGO', 'assets/img/developer-logo.png');

$isProduction = (strpos($_SERVER['HTTP_HOST'] ?? '', 'localhost') === false && 
                strpos($_SERVER['HTTP_HOST'] ?? '', '127.0.0.1') === false);

if ($isProduction) {
    if (!defined('DB_HOST')) define('DB_HOST', 'localhost');
    if (!defined('DB_NAME')) define('DB_NAME', 'adfb2574_pwf_po_system');
    if (!defined('DB_USER')) define('DB_USER', 'adfb2574_pwf_user');
    if (!defined('DB_PASS')) define('DB_PASS', '@Nnoc2025');
} else {
    if (!defined('DB_HOST')) define('DB_HOST', 'localhost');
    if (!defined('DB_NAME')) define('DB_NAME', 'pwf_po_system');
    if (!defined('DB_USER')) define('DB_USER', 'root');
    if (!defined('DB_PASS')) define('DB_PASS', '');
}
if (!defined('DB_CHARSET')) define('DB_CHARSET', 'utf8mb4');

if (!defined('BASE_PATH')) define('BASE_PATH', dirname(dirname(__FILE__)));

$host = $_SERVER['HTTP_HOST'] ?? 'localhost';
$port = $_SERVER['SERVER_PORT'] ?? '80';
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';

if (!defined('BASE_URL')) {
    if (php_sapi_name() !== 'cli') {
        $scriptDir = dirname($_SERVER['SCRIPT_NAME'] ?? '');
        $basePath = '';
        
        if (strpos($_SERVER['HTTP_HOST'] ?? '', 'localhost') !== false || 
            strpos($_SERVER['HTTP_HOST'] ?? '', '127.0.0.1') !== false) {
            $basePath = '/narayanakarimunjawa/pwf_po_system';
        } else {
            $basePath = '';
        }
        
        define('BASE_URL', $protocol . '://' . $host . $basePath);
    } else {
        define('BASE_URL', 'http://localhost/pwf_po_system');
    }
}

date_default_timezone_set('Asia/Jakarta');

if ($isProduction) {
    error_reporting(0);
    ini_set('display_errors', 0);
    ini_set('log_errors', 1);
} else {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
}

if (!defined('CURRENCY_SYMBOL')) define('CURRENCY_SYMBOL', 'Rp');
if (!defined('CURRENCY_DECIMAL')) define('CURRENCY_DECIMAL', 0);

require_once dirname(__FILE__) . '/database.php';
CONFIG;

// Cek apakah folder target ada
if (!is_dir($targetDir . '/config')) {
    echo "❌ ERROR: Folder " . htmlspecialchars($targetDir . '/config') . " tidak ditemukan!\n";
    echo "Pastikan folder pwf-po-system sudah di-clone.\n";
    $success = false;
} else {
    // Write config
    if (@file_put_contents($configPath, $configContent) !== false) {
        echo "✅ config.php berhasil dibuat/update\n";
        echo "   Lokasi: " . htmlspecialchars($configPath) . "\n";
    } else {
        echo "❌ ERROR: Tidak bisa menulis config.php\n";
        echo "   Periksa permission folder config/ (harus writable)\n";
        $success = false;
    }
}

// ===== STEP 2: Test Database Connection =====
echo "\n[STEP 2] Testing database connection...\n";

if ($success) {
    try {
        $pdo = new PDO(
            'mysql:host=localhost;dbname=adfb2574_pwf_po_system;charset=utf8mb4',
            'adfb2574_pwf_user',
            '@Nnoc2025',
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        echo "✅ Database connection OK!\n";
        echo "   Database: adfb2574_pwf_po_system\n";
        echo "   User: adfb2574_pwf_user\n";
    } catch (Exception $e) {
        echo "❌ ERROR: Database connection failed!\n";
        echo "   Error: " . htmlspecialchars($e->getMessage()) . "\n";
        $success = false;
    }
}

// ===== STEP 3: Import Database Schema =====
echo "\n[STEP 3] Import database schema...\n";

if ($success && file_exists($databasePath)) {
    try {
        $sqlContent = file_get_contents($databasePath);
        $statements = array_filter(
            array_map('trim', explode(';', $sqlContent)),
            fn($s) => !empty($s) && !str_starts_with($s, '--') && !str_starts_with($s, '/*')
        );
        
        $importedCount = 0;
        foreach ($statements as $statement) {
            try {
                $pdo->exec($statement);
                $importedCount++;
            } catch (Exception $e) {
                // Skip errors untuk duplicate table atau constraints
                if (strpos($e->getMessage(), 'already exists') === false) {
                    throw $e;
                }
            }
        }
        
        echo "✅ Database schema imported!\n";
        echo "   Statements executed: " . count($statements) . "\n";
        echo "   Success: " . $importedCount . "\n";
    } catch (Exception $e) {
        echo "⚠️  WARNING: Import failed\n";
        echo "   Error: " . htmlspecialchars($e->getMessage()) . "\n";
        echo "   Coba import manually via phpMyAdmin\n";
    }
} else if ($success && !file_exists($databasePath)) {
    echo "⚠️  WARNING: database.sql tidak ditemukan\n";
    echo "   File: " . htmlspecialchars($databasePath) . "\n";
    echo "   Coba import manual via phpMyAdmin\n";
}

// ===== FINAL STATUS =====
echo "\n" . str_repeat("=", 60) . "\n";
if ($success) {
    echo "✅ PWF PO SYSTEM SETUP COMPLETE!\n";
    echo "\nNext steps:\n";
    echo "1. Buka: https://adfsystem.online/pwf-po-system/\n";
    echo "2. Atau setup domain pwfoffice.com di cPanel\n";
    echo "3. Hapus file setup-pwf.php setelah selesai (untuk security)\n";
} else {
    echo "❌ SETUP FAILED - Lihat error di atas\n";
}
echo str_repeat("=", 60) . "\n";

echo "</pre>";

// Auto-delete script after 5 minutes (security)
echo "<p style='color: red; margin-top: 20px;'>";
echo "⚠️ <strong>Security:</strong> Hapus file ini (setup-pwf.php) setelah setup selesai!<br>";
echo "Script ini akan dihapus otomatis dalam 5 menit untuk keamanan.";
echo "</p>";

// Log setup time untuk auto-delete
$setupMarkerFile = $targetDir . '/.setup_done';
if ($success) {
    @file_put_contents($setupMarkerFile, time());
}
?>
